In [1]:
import numpy as np
import torch

In [2]:
nv = np.array([[1,2,3,4]])
print(nv), print(" ")
print(nv.T, " \n")

nvT = nv.T

print(nvT.T)

[[1 2 3 4]]
 
[[1]
 [2]
 [3]
 [4]]  

[[1 2 3 4]]


In [3]:
nv = np.array([[1,2,3,4],
               [1,3,5,6]])
print(nv), print(" ")
print(nv.T, " \n")

nvT = nv.T

print(nvT.T)

[[1 2 3 4]
 [1 3 5 6]]
 
[[1 1]
 [2 3]
 [3 5]
 [4 6]]  

[[1 2 3 4]
 [1 3 5 6]]


In [4]:
tv = torch.tensor([[1,2,3,4]])

print(tv)

print("\n", tv.T)

tensor([[1, 2, 3, 4]])

 tensor([[1],
        [2],
        [3],
        [4]])


In [5]:
type(nv)

numpy.ndarray

In [6]:
type(tv)

torch.Tensor

### Dot Product

In [7]:
nv1 = np.array([1,2,3,4])
nv2 = np.array([0,1,0,-1])

print(np.dot(nv1,nv2))


print(np.sum(nv1*nv2))

-2
-2


# Matriz multiplication

In [12]:
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

In [14]:
A@B

array([[ 1.74271503, -1.19923295, -0.37153994, -0.82039606, -0.17927421],
       [ 0.86002074, -0.13629893,  0.06833843, -0.67704647, -0.73868273],
       [ 0.97516967, -1.5559765 , -0.61345755, -0.36372534,  0.60541531]])

In [16]:
np.round(np.matmul(A,B), 2)

array([[ 1.74, -1.2 , -0.37, -0.82, -0.18],
       [ 0.86, -0.14,  0.07, -0.68, -0.74],
       [ 0.98, -1.56, -0.61, -0.36,  0.61]])

In [27]:
A = torch.randn(3,4)
B = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor(C1, dtype=torch.float)
A@C2

tensor([[ 1.8242, -0.4668, -3.3057,  0.0376, -4.5334,  0.5235, -1.0320],
        [-0.8414,  2.1278, -2.3030, -2.9069,  4.6278, -0.5381,  6.6691],
        [-1.6619,  1.9180,  1.9419, -0.6706,  7.6695, -1.1222,  7.2173]])

# Softmax

In [32]:
v = np.random.randn(4)

v_exp = np.exp(v)
soma = np.sum(v_exp)
resultado = v_exp/soma
print(v)
print(resultado)

[0.48630298 2.67366919 0.10664339 0.22025157]
[0.08801109 0.78432936 0.06020788 0.06745167]


In [33]:
softfun = torch.nn.Softmax(dim=0)
softfun

Softmax(dim=0)

In [35]:
res = softfun(torch.Tensor(v))
res

tensor([0.0880, 0.7843, 0.0602, 0.0675])