In [101]:
import torch

In [102]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [103]:
x.numel()

12

In [104]:
x.shape

torch.Size([12])

In [105]:
X=x.reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [106]:
X.shape

torch.Size([3, 4])

In [107]:
x.reshape(-1,4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [108]:
x.reshape(3,-1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [109]:
torch.linspace(0,10, 11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [110]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [111]:
torch.ones((2,2,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [112]:
torch.randn(3,4)

tensor([[-0.1187,  0.6774, -1.1144,  0.7440],
        [-0.7123,  0.3767,  0.5188,  0.0830],
        [ 0.5165,  1.0162,  1.4852, -1.0739]])

In [113]:
Z = torch.zeros(2,2)
X = torch.ones(2,2)
C = torch.full((2,2), 9)
Z,X,C

(tensor([[0., 0.],
         [0., 0.]]),
 tensor([[1., 1.],
         [1., 1.]]),
 tensor([[9, 9],
         [9, 9]]))

In [114]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])


tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [115]:
X

tensor([[1., 1.],
        [1., 1.]])

In [116]:
X[-1],X[1:3]

(tensor([1., 1.]), tensor([[1., 1.]]))

In [117]:
X[:,0]

tensor([1., 1.])

In [118]:
torch.exp(x)

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

In [119]:
x = torch.tensor([1., 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [120]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [121]:
torch.cat((X,Y), dim=0), torch.cat((X,Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [122]:
torch.cat((X,Y), dim=0).shape, torch.cat((X,Y), dim=1).shape

(torch.Size([6, 4]), torch.Size([3, 8]))

In [123]:
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [124]:
X.sum()

tensor(66.)

In [125]:
before = id(Y)
Y = Y + X
id(Y) == before


False

In [126]:
a = torch.arange(9).reshape(3,1,3)
b= torch.arange(9).reshape(3,3,1)
a,b

(tensor([[[0, 1, 2]],
 
         [[3, 4, 5]],
 
         [[6, 7, 8]]]),
 tensor([[[0],
          [1],
          [2]],
 
         [[3],
          [4],
          [5]],
 
         [[6],
          [7],
          [8]]]))

In [127]:
a + b

tensor([[[ 0,  1,  2],
         [ 1,  2,  3],
         [ 2,  3,  4]],

        [[ 6,  7,  8],
         [ 7,  8,  9],
         [ 8,  9, 10]],

        [[12, 13, 14],
         [13, 14, 15],
         [14, 15, 16]]])

In [128]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [129]:
Z = torch.zeros_like(Y)
before = id(Z)
Z[:] = X + Y
id(Z) == before

True

In [130]:
before = id(X)
X += Y
id(X) == before


True

In [131]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [132]:
B[0][0] = 0
A, B

(array([[ 0.,  4., 10., 12.],
        [13., 17., 21., 25.],
        [28., 30., 32., 34.]], dtype=float32),
 tensor([[ 0.,  4., 10., 12.],
         [13., 17., 21., 25.],
         [28., 30., 32., 34.]]))

In [133]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [ ]:
id1 = id(Y)
Y = X + Y
id2 = id(Y)
Y += X
id1 == id2, id(Y) == id2



True