In [1]:
import torch

In [2]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y


(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [3]:
x = torch.tensor([0,1,2])
x

tensor([0, 1, 2])

In [4]:
x[2]

tensor(2)

In [5]:
len(x)

3

In [6]:
x.shape

torch.Size([3])

In [7]:
A = torch.arange(6).reshape(3,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [8]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [9]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T


tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [10]:
torch.arange(24).reshape(2, 3, 4)


tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [11]:
A = torch.arange(6, dtype=torch.float32).reshape(2,3)
B = A.clone()
A, A+B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [12]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [13]:
2 + A, 2*A

(tensor([[2., 3., 4.],
         [5., 6., 7.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [32]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [ ]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [ ]:
A.shape, A.sum(axis=1)

(torch.Size([2, 3]), tensor([ 3., 12.]))

In [18]:
A.shape, A.sum(axis=1).shape

(torch.Size([2, 3]), torch.Size([2]))

In [20]:
A.mean(axis=0), A.sum(axis=0)/A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

In [22]:
A, A.sum(axis=1), A.sum(axis=1, keepdim=True)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([ 3., 12.]),
 tensor([[ 3.],
         [12.]]))

In [24]:
A/A.sum(axis=1, keepdim=True)

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [28]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

In [35]:
y = torch.ones(3, dtype=torch.float32)
x, y, torch.dot(x,y), x@y

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.), tensor(3.))

In [38]:
torch.sum(x * y)

tensor(3.)

In [43]:
A, x, torch.mv(A,x), A@x

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([0., 1., 2.]),
 tensor([ 5., 14.]),
 tensor([ 5., 14.]))

In [46]:
x = torch.tensor([[0],[1],[2]], dtype=torch.float32)
A, x, A@x

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[0.],
         [1.],
         [2.]]),
 tensor([[ 5.],
         [14.]]))

In [ ]:
B = torch.ones(3, 4)
A, B, A@B


(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

In [47]:
u = torch.tensor([3., -4.])
torch.norm(u)

tensor(5.)

In [48]:
torch.abs(u).sum()

tensor(7.)

In [50]:
torch.norm(torch.ones((4,9)))

tensor(6.)

1)
Sendo a_ij o elemennto de A na linah i e coluna j e b_ij sendo o mesmo para B, B = A.T a definição da transposição é a_ij = b_ji da mesma forma se tiraramos a transposição de B como C = B.T, teremos b_ij = c_ji, o que é o mesmo que c_ij = b_ji, e como vimos anterisomente a_ij = b_ji, logo c_ij = a_ij, portanto A.T.T = A