In [1]:
from sklearn.datasets import load_iris

X = load_iris()

In [2]:
y = X.target
X = X.data

In [3]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
import numpy as np
X_bias = np.c_[np.ones([len(X), 1]), X]

In [5]:
X_bias

array([[1. , 5.1, 3.5, 1.4, 0.2],
       [1. , 4.9, 3. , 1.4, 0.2],
       [1. , 4.7, 3.2, 1.3, 0.2],
       [1. , 4.6, 3.1, 1.5, 0.2],
       [1. , 5. , 3.6, 1.4, 0.2],
       [1. , 5.4, 3.9, 1.7, 0.4],
       [1. , 4.6, 3.4, 1.4, 0.3],
       [1. , 5. , 3.4, 1.5, 0.2],
       [1. , 4.4, 2.9, 1.4, 0.2],
       [1. , 4.9, 3.1, 1.5, 0.1],
       [1. , 5.4, 3.7, 1.5, 0.2],
       [1. , 4.8, 3.4, 1.6, 0.2],
       [1. , 4.8, 3. , 1.4, 0.1],
       [1. , 4.3, 3. , 1.1, 0.1],
       [1. , 5.8, 4. , 1.2, 0.2],
       [1. , 5.7, 4.4, 1.5, 0.4],
       [1. , 5.4, 3.9, 1.3, 0.4],
       [1. , 5.1, 3.5, 1.4, 0.3],
       [1. , 5.7, 3.8, 1.7, 0.3],
       [1. , 5.1, 3.8, 1.5, 0.3],
       [1. , 5.4, 3.4, 1.7, 0.2],
       [1. , 5.1, 3.7, 1.5, 0.4],
       [1. , 4.6, 3.6, 1. , 0.2],
       [1. , 5.1, 3.3, 1.7, 0.5],
       [1. , 4.8, 3.4, 1.9, 0.2],
       [1. , 5. , 3. , 1.6, 0.2],
       [1. , 5. , 3.4, 1.6, 0.4],
       [1. , 5.2, 3.5, 1.5, 0.2],
       [1. , 5.2, 3.4, 1.4, 0.2],
       [1. , 4

In [6]:
test_ratio = 0.2
validation_ratio = 0.2
total_size = len(X_bias)

test_size = int(total_size * test_ratio)
validation_size = int(total_size * validation_ratio)
train_size = total_size - test_size - validation_size

rnd_indices = np.random.permutation(total_size)

X_train = X_bias[rnd_indices[:train_size]]
y_train = y[rnd_indices[:train_size]]
X_valid = X_bias[rnd_indices[train_size:-test_size]]
y_valid = y[rnd_indices[train_size:-test_size]]
X_test = X_bias[rnd_indices[-test_size:]]
y_test = y[rnd_indices[-test_size:]]


In [7]:
def one_hot(vetor):
    colunas = vetor.max() + 1
    linhas = len(vetor)
    y_one_hot = np.zeros((linhas, colunas))
    for i in range(linhas):
        y_one_hot[i, vetor[i]] = 1
    return y_one_hot

one_hot(y_train[:10])

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [8]:
y_train_one = one_hot(y_train)
y_valid_one = one_hot(y_valid)
y_test_one = one_hot(y_test)

In [9]:
def softmax(logits):
    exps = np.exp(logits)
    exp_sums = np.sum(exps, axis=1, keepdims=True)
    return exps / exp_sums
    

In [10]:
n_inputs = X_train.shape[1]
n_outputs = len(np.unique(y_train))
print(n_inputs, n_outputs)


5 3


In [11]:
Theta = np.random.randn(n_inputs, n_outputs)
eta = 0.01

logits = X_train.dot(Theta)
y_proba = softmax(logits)
y_proba

array([[9.99999584e-01, 4.16178376e-07, 2.38237148e-18],
       [1.00000000e+00, 2.42273025e-10, 2.37319495e-16],
       [9.99998385e-01, 1.61451201e-06, 3.33667793e-16],
       [9.99998745e-01, 1.25475458e-06, 3.20374756e-16],
       [1.00000000e+00, 3.26958994e-13, 5.52540248e-20],
       [9.99996731e-01, 3.26936887e-06, 6.04844755e-15],
       [9.99999999e-01, 8.75661287e-10, 1.82343688e-17],
       [9.99999095e-01, 9.05314932e-07, 1.74738575e-16],
       [9.99999996e-01, 3.65310950e-09, 1.50482543e-16],
       [9.99999994e-01, 5.69762592e-09, 2.55128159e-16],
       [1.00000000e+00, 4.51170378e-12, 1.52202761e-19],
       [1.00000000e+00, 2.47193387e-11, 7.60730188e-18],
       [1.00000000e+00, 1.39169209e-11, 1.65595978e-19],
       [9.99999995e-01, 4.61491161e-09, 2.88347863e-14],
       [9.99998969e-01, 1.03076739e-06, 7.21701486e-16],
       [1.00000000e+00, 1.22416383e-10, 1.57409561e-18],
       [1.00000000e+00, 8.66536195e-11, 1.74406878e-19],
       [1.00000000e+00, 8.74590

In [12]:
error = y_proba - y_train_one
error

array([[-4.16178376e-07,  4.16178376e-07,  2.38237148e-18],
       [ 1.00000000e+00,  2.42273025e-10, -1.00000000e+00],
       [-1.61451201e-06,  1.61451201e-06,  3.33667793e-16],
       [-1.25475458e-06,  1.25475458e-06,  3.20374756e-16],
       [ 1.00000000e+00,  3.26958994e-13, -1.00000000e+00],
       [-3.26936888e-06,  3.26936887e-06,  6.04844755e-15],
       [ 9.99999999e-01, -9.99999999e-01,  1.82343688e-17],
       [-9.05314932e-07,  9.05314932e-07,  1.74738575e-16],
       [ 9.99999996e-01, -9.99999996e-01,  1.50482543e-16],
       [ 9.99999994e-01, -9.99999994e-01,  2.55128159e-16],
       [ 1.00000000e+00,  4.51170378e-12, -1.00000000e+00],
       [ 1.00000000e+00,  2.47193387e-11, -1.00000000e+00],
       [ 1.00000000e+00,  1.39169209e-11, -1.00000000e+00],
       [ 9.99999995e-01,  4.61491161e-09, -1.00000000e+00],
       [-1.03076739e-06,  1.03076739e-06,  7.21701486e-16],
       [ 1.00000000e+00, -1.00000000e+00,  1.57409561e-18],
       [ 1.00000000e+00, -1.00000000e+00

In [13]:
gradients = 1/len(X_train) * X_train.T.dot(error)

Theta = Theta - eta * gradients

In [14]:
epochs = 40000
Theta = np.random.randn(n_inputs, n_outputs)
eta = 0.01
epsilon = 1e-7
print_interval = 10000

for epoch in range(epochs):
    scores = X_train.dot(Theta)
    
    y_proba = softmax(scores)
    error = y_proba - y_train_one
    
    gradients = 1/len(X_train) * X_train.T.dot(error)
    
    if (epoch % print_interval) == 0:
        loss = -np.mean(np.sum(y_train_one * np.log(y_proba + epsilon), axis=1))
        print("Epoch: ", epoch, " Loss: ", loss)
    
    Theta -= gradients * eta
    


Epoch:  0  Loss:  5.03034628548041
Epoch:  10000  Loss:  0.08291931613931414
Epoch:  20000  Loss:  0.053729724051948764
Epoch:  30000  Loss:  0.0417932890482392


In [15]:
val = X_train[0]
print(val, y_train[0])

[1.  5.8 4.  1.2 0.2] 0


In [16]:
y_score = X_test.dot(Theta)
y_pred = np.argmax(y_score, axis=1)

from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)

0.9333333333333333

In [17]:
val = X_test[1]
y = y_test[1]

val

array([1. , 5. , 3.3, 1.4, 0.2])